language: generic
sudo: required
services: 
  - docker
before_install:
  - docker build -t nomad20/docker-reactDef -f Dockerfile.dev .
scripts:
  - docker run -e CI=true nomad20/docker-reactDef -- --coverage